### ISSUE TITLE
get_harvesters completely messes up the node 

### ISSUE THREAD

**Issue by mmitech** [Chia-Network/chia-exporter#121]
the newer version of the exporter relies on getting all info from the farmer, however, the get_harvesters call is so heavy that it always times out and messes up farming completely, when the timeout limit is increased the node just stops working at some point

![image](https://github.com/Chia-Network/chia-exporter/assets/4456920/b624ed1e-0539-4714-b6d6-8b15df398ff5)
![image](https://github.com/Chia-Network/chia-exporter/assets/4456920/9a2b027f-a725-4773-9fa3-9de80e93187d)
![image](https://github.com/Chia-Network/chia-exporter/assets/4456920/82eac81e-4ff6-4717-912d-cfa83b38341c)

**Comment by cmmarslender** [comment]
What version of Chia are you running on?

**Comment by mmitech** [comment]
> What version of Chia are you running on?

I am using the latest version of Gigahorse which is based on 2.1.1

**Comment by mmitech** [comment]
> I just published a new RC https://github.com/Chia-Network/chia-exporter/releases/tag/0.10.3-rc1
> 
> It wont be able to help anything around the loading behavior w/ GH, but it does ensure that chia-exporter doesn't start stacking requests for the harvester data if the timeout is set to a higher value (only will have one active request at a time).
> 
> Do you want to see if the RC helps the node problem?

yes sure I will try it now

**Comment by mmitech** [comment]
OK it does just a bit better, but the main issue remains, the performance hit is just unavoidable 

![image](https://github.com/Chia-Network/chia-exporter/assets/4456920/87248d17-6633-4b4d-857b-cb7c36715b25)
![image](https://github.com/Chia-Network/chia-exporter/assets/4456920/f07d65fc-298e-464a-9b6b-219017d9cd40)

**Comment by cmmarslender** [comment]
before the option to get this data from the farmer existed, did you have this deployed to all your harvesters to get the plot data (I guess this is assuming you have multiple harvesters, maybe a bad assumption). If so, curious how that performed. If you have multiple harvesters, I imagine it was a bit better, since it was just getting data about each from the harvester directly, vs trying to get ALL the data from once location. That approach (adding to each harvester) is still supported, so I could always add an option to just disable the farmer based collection for cases like this, or possibly an option to limit how frequently it is checked. I'm not sure the performance of this is going to be something I can improve all that much for very large farms.

**Comment by mmitech** [comment]
yes, before upgrading to the latest I had exporter installed in every harvester and it worked greatly, never experienced any issues before.

So basically if I just deploy the exporter back on all nodes this should start working fine or is there any option I need to add for it to work like it used to before?

**Comment by cmmarslender** [comment]
The dashboard is possibly going to be an issue, now that you mention that.. but maybe we can update it to use farmer based metrics if present, otherwise try harvester based metrics (they have different prefixes, based on the source). Let me update exporter first, then I'll take a look at the dashboard.

**Comment by mmitech** [comment]
> `--disable-central-harvester-collection`

OK, I can confirm this works great, now the dashboard doesn't work properly.

![image](https://github.com/Chia-Network/chia-exporter/assets/4456920/077ec99b-bf1c-475e-a968-2fe7e85bd80d)
