### ISSUE TITLE
read C:\Users\ABC/.chia/mainnet: The handle is invalid

### ISSUE THREAD

**Issue by mazm786** [Chia-Network/chia-exporter#28]
Command Prompt is started with Admin User. 
Chia version 1.3.3
OS: Windows 10

Following data is copied from Command line
```
C:\Users\ABC\Downloads\chia-exporter-windows-amd64>chia-exporter serve
2022/04/19 13:52:01 read C:\Users\ABC/.chia/mainnet: **The handle is invalid.**
```
**Please Note slash in path before .chia folder:** C:\Users\ABC/.chia/mainnet
Running OK on one PC while problem in 2nd PC.

**Comment by stefan-lange** [comment]
I have the 'same' problem with 0.0.7, 0.0.5 was working fine.
Docker / debian 10
Error '... read /home/chia/.chia/mainnet: is a directory'

I played with the CHIA_ROOT env var to get this fixed (added trailing slash etc.), but it doesn't work.

**Comment by stefan-lange** [comment]
By 'config files' do you mean the config.yaml? If so on my side it is
/home/chia/.chia/mainnet/config/config.yaml
I don't have any custom config file for the exporter

echo $CHIA_ROOT
/home/chia/.chia/mainnet

**Comment by cmmarslender** [comment]
Thanks. Are you using the official chia docker image, or another variant?

**Comment by stefan-lange** [comment]
100% custom image

**Comment by cmmarslender** [comment]
I think these are failing (with admittedly pretty bad error messages, improvements to those on the way) because your config files are missing a new section for the seeder https://github.com/Chia-Network/chia-blockchain/blob/main/chia/util/initial-config.yaml#L134

I'm working on improving the error message for this case so its obvious what the problem is, as well as making the client that is failing to start optional for now, since its just used for the ip/country data if scraping w/ a crawler

**Comment by cmmarslender** [comment]
Published https://github.com/Chia-Network/chia-exporter/releases/tag/0.0.8

Let me know if that doesn't solve your issues

**Comment by stefan-lange** [comment]
0.0.8 works for me, thx!
