### ISSUE TITLE
feature request: support remote harvesters by using chia rpc farmer get_harvesters 

### ISSUE THREAD

**Issue by CharlieTemplar** [Chia-Network/chia-exporter#72]
My farm doesn't have a single local plot, but instead, many remote harvesters.
Instead of using `harvester get_plots`, `farmer get_harvesters` returns exactly the same plot details but for ALL harvesters and broken down by harvester, so we can get at all the data with a single rpc call.

**Comment by cmmarslender** [comment]
I think this will be doable, but right now its only possible with polling, and I try and avoid polling wherever possible. I have a PR open on chia-blockchain (https://github.com/Chia-Network/chia-blockchain/pull/14419) that passes along more events to `metrics` that I'll be able to then hook in here with and do this only when necessary. I'm not sure if this is going to make it to the 1.7.0 release, so the functionality in chia-exporter may need to wait until the following chia release.

**Comment by xklech** [comment]
Hello, I would like to ping this feature request, also have several remote harvesters. Mentioned Merge request was merged on January so this should be unblocked.

**Comment by cmmarslender** [comment]
Looking into the data available from the farmer `get_harvesters` RPC, it looks like only a subset of the data we typically report for harvesters will be available there. Can get total plot count, plot count by k size, and total plot filesize from that endpoint. There is additional data that is reported when this is installed on the harvesters: total found proofs (counter since exporter started), last found proofs (how many proofs were found for the last event), total eligible plots (counter since exporter started), last eligible plots (number eligible for last event), last lookup time, connection_count

So the recommendation is still to install chia-exporter on all of your remote harvesters and set up scrape targets in prometheus to get the most detailed set of metrics, but it still may be worth getting the basic info from the main farmer
